# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2da74056741f6368a47d53d9846d432f4127f6160f256f0bdbef5e18cda1286e1cccc22e8329eef5443a2c74626a1b3f0758c3ea8b3e2d6d8a8d89fdbeccdcd

test:
  secret_key_base: cfad9d04d6a0268cf3b25b5022759adbbf0b99964aa9de8696dd647e02fba4a29df83af22e3f95a868bb4738570c045419ab9b438c90dead255c45a17eaadaa3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
